services:
  postgres:
    image: postgres:13
    ports:
      - "8585:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "content-catalog", "-U", "ps_user" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    ports:
      - "6333:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "9930:2181"
  kafka:
    image: wurstmeister/kafka:0.10.1.0-2
    ports:
      - "9940:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9940
      KAFKA_CREATE_TOPICS: "consumer:1:1,consumergcm:1:1,consumerapns:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

